### ISSUE TITLE
Signing workloads on CentOS Stream 8 & RHEL 8 failed with sign_with_file() got an unexpected keyword argument 'password'

### ISSUE THREAD

**Issue by anjalirai-intel** [gramineproject/gramine#1532]
### Description of the problem

With latest Gramine master, All unit tests and workloads are failed during signing key

### Steps to reproduce

1. Build Gramine with latest master
2. cd CI-Examples/helloworld
3. make SGX=1 ARCH_LIBDIR=/lib64

### Expected results

gramine-sgx-sign should be successful and workload should be executed with gramine-sgx

### Actual results

```
cc -Wall -Wextra -O3   -c -o helloworld.o helloworld.c
cc   helloworld.o   -o helloworld
gramine-manifest \
        -Dlog_level=error \
        helloworld.manifest.template helloworld.manifest
gramine-sgx-sign \
        --manifest helloworld.manifest \
        --output helloworld.manifest.sgx
Traceback (most recent call last):
  File "/home/intel/anjali/gramine/gramine_install/usr/bin/gramine-sgx-sign", line 139, in <module>
    main() # pylint: disable=no-value-for-parameter
  File "/usr/lib/python3.6/site-packages/click/core.py", line 721, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 894, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/intel/anjali/gramine/gramine_install/usr/bin/gramine-sgx-sign", line 71, in main
    ret = get_sgx_sign_plugin(with_)(args=plugin_args, standalone_mode=False)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 721, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 894, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
TypeError: sign_with_file() got an unexpected keyword argument 'password'
make: *** [Makefile:44: sgx_sign] Error 1
```

### Gramine commit hash

39b529fbf88b77a33b5e625e4d9ed4a6a8d7d7af

**Comment by dimakuv** [comment]
That's a weird one. I tried to search in the internet, but couldn't find an example similar to ours.

So, the offending lines are these: https://github.com/gramineproject/gramine/blob/bc11ecbaf969ec237e05b3269b7b4299c4af966d/python/graminelibos/sgx_sign.py#L553-L555

What happens here is that we have two aliases (two option names) for the `passphrase`/`password` Click option. But we use only the first option as the func argument to `sign_with_file()`. According to the Click documentation, that's exactly what should happen: https://click.palletsprojects.com/en/8.1.x/options/#name-your-options (read the second item in the list).

I think all our CI tests are with Python 3.8 or higher (and Click 8.1). I'm assuming there is some bug in Python 3.6 and Click whatever-version-is-used-for-3.6. But I didn't find a bug report or anything on the internet.

@woju Looks like an issue for your brains.

**Comment by dimakuv** [comment]
@anjalirai-intel What is the Click version you have? `pip3 show click`.

**Comment by anjalirai-intel** [comment]
Name: click
Version: 6.7
Summary: A simple wrapper around optparse for powerful command line utilities.
Home-page: http://github.com/mitsuhiko/click
Author: Armin Ronacher
Author-email: armin.ronacher@active-4.com
License: UNKNOWN
Location: /usr/lib/python3.6/site-packages
Requires:

**Comment by dimakuv** [comment]
Comparing the two Click documentation pages:
- https://click.palletsprojects.com/en/6.x/options/ (your old Click version)
- https://click.palletsprojects.com/en/8.1.x/options/ (our tested new Click version)

Looks like Click 6.7 cannot recognize patterns like ` @click.option('--passphrase', '--password', ...)`, and goes bananas.

@anjalirai-intel For experimentation purposes, could you update Click to a later version in your CentOS/RHEL systems?

**Comment by anjalirai-intel** [comment]
I tried the experiment after installing click 8.0.4 and it worked

```
[intel@ocsbesrhlrepo01 helloworld]$ sudo python3 -m pip install click==8.0.4
WARNING: Running pip install with root privileges is generally not a good idea. Try `__main__.py install --user` instead.
Collecting click==8.0.4
  Downloading https://files.pythonhosted.org/packages/4a/a8/0b2ced25639fb20cc1c9784de90a8c25f9504a7f18cd8b5397bd61696d7d/click-8.0.4-py3-none-any.whl (97kB)
    100% |████████████████████████████████| 102kB 2.3MB/s 
Collecting importlib-metadata; python_version < "3.8" (from click==8.0.4)
  Downloading https://files.pythonhosted.org/packages/a0/a1/b153a0a4caf7a7e3f15c2cd56c7702e2cf3d89b1b359d1f1c5e59d68f4ce/importlib_metadata-4.8.3-py3-none-any.whl
Collecting typing-extensions>=3.6.4; python_version < "3.8" (from importlib-metadata; python_version < "3.8"->click==8.0.4)
  Downloading https://files.pythonhosted.org/packages/45/6b/44f7f8f1e110027cf88956b59f2fad776cca7e1704396d043f89effd3a0e/typing_extensions-4.1.1-py3-none-any.whl
Collecting zipp>=0.5 (from importlib-metadata; python_version < "3.8"->click==8.0.4)
  Downloading https://files.pythonhosted.org/packages/bd/df/d4a4974a3e3957fd1c1fa3082366d7fff6e428ddb55f074bf64876f8e8ad/zipp-3.6.0-py3-none-any.whl
Installing collected packages: typing-extensions, zipp, importlib-metadata, click
Successfully installed click-8.0.4 importlib-metadata-4.8.3 typing-extensions-4.1.1 zipp-3.6.0


[intel@ocsbesrhlrepo01 helloworld]$ make clean && make SGX=1 ARCH_LIBDIR=/lib64
rm -f *.token *.sig *.manifest.sgx *.manifest helloworld.o helloworld OUTPUT
cc -Wall -Wextra -O3   -c -o helloworld.o helloworld.c
cc   helloworld.o   -o helloworld
gramine-manifest \
        -Dlog_level=error \
        helloworld.manifest.template helloworld.manifest
gramine-sgx-sign \
        --manifest helloworld.manifest \
        --output helloworld.manifest.sgx
Attributes:
    size:        0x10000000
    edmm:        False
    max_threads: 4
    isv_prod_id: 0
    isv_svn:     0
    attr.flags:  0x6
    attr.xfrm:   0x3
    misc_select: 0x0
SGX remote attestation:
    None
Memory:
    000000000fffd000-0000000010000000 [REG:R--] (manifest) measured
    000000000ffdd000-000000000fffd000 [REG:RW-] (ssa) measured
    000000000ffd9000-000000000ffdd000 [TCS:---] (tcs) measured
    000000000ffd5000-000000000ffd9000 [REG:RW-] (tls) measured
    000000000ff95000-000000000ffd5000 [REG:RW-] (stack) measured
    000000000ff55000-000000000ff95000 [REG:RW-] (stack) measured
    000000000ff15000-000000000ff55000 [REG:RW-] (stack) measured
    000000000fed5000-000000000ff15000 [REG:RW-] (stack) measured
    000000000fec5000-000000000fed5000 [REG:RW-] (sig_stack) measured
    000000000feb5000-000000000fec5000 [REG:RW-] (sig_stack) measured
    000000000fea5000-000000000feb5000 [REG:RW-] (sig_stack) measured
    000000000fe95000-000000000fea5000 [REG:RW-] (sig_stack) measured
    000000000fc3f000-000000000fc8c000 [REG:R-X] (code) measured
    000000000fe8b000-000000000fe95000 [REG:RW-] (data) measured
    0000000000010000-000000000fc3f000 [REG:RWX] (free)
Measurement:
    6c6f4b834047f754153c606f260c168aa8e790c403bd8dc521cae96cd7c899d2
```

**Comment by anjalirai-intel** [comment]
@woju Any updates on this issue

**Comment by woju** [comment]
@anjalirai-intel Please test #1540

**Comment by anjalirai-intel** [comment]
@woju I tested #1540  with RHEL 8 distro, gramine-sgx-sign was working and I was able to run workloads
