### ISSUE TITLE
[LibOS] inotify API

### ISSUE THREAD

**Issue by lead4good** [gramineproject/gramine#310]
If flock and the mlock family of syscalls is emulated (#308, #309) most dotnet applications currently fail due to the FileSystemWatcher's inotify dependency. I wonder whether there are any security issues if for chrootfs (and possibly protected fs) gramine would just pass through the events of the untrusted linux kernel?

```
[P1:T1:RPCServer] warning: Unsupported system call inotify_init
Unhandled exception. 
System.IO.IOException: Function not implemented
   at System.IO.FileSystemWatcher.StartRaisingEvents()
   at System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed()
   at System.IO.FileSystemWatcher.set_EnableRaisingEvents(Boolean value)
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.TryEnableFileSystemWatcher()
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.CreateFileChangeToken(String filter)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider.Watch(String filter)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.<.ctor>b__1_0()
   at Microsoft.Extensions.Primitives.ChangeToken.ChangeTokenRegistration`1..ctor(Func`1 changeTokenProducer, Action`1 changeTokenConsumer, TState state)
   at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider..ctor(FileConfigurationSource source)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build(IConfigurationBuilder builder)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at RPCServer.Program.Main(String[] args) in /workspace/Program.cs:line 16
```

**Comment by dimakuv** [comment]
Reading through `man inotify`, I see that this Linux sub-system is quite complicated.

In particular, implementing correct handling of `poll(<inotify-fd>)` will not be straight-forward in Gramine.

My quick assessment: implementing `inotify` will require substantial changes in Gramine codebase. That's because `inotify` is not just a couple of new syscalls (`inotify_init`, `inotify_add_watch`, etc) but also modifications to the existing syscalls like `read`, `write`, `select`, `poll`.

> I wonder whether there are any security issues if for chrootfs (and possibly protected fs) gramine would just pass through the events of the untrusted linux kernel?

If you just want to implement pass-through of `chrootfs` files, it may be possible, but would still require quite some work to maintain internal Gramine state (you'll need to carefully update metadata of inotified chrootfs files). I don't see immediate problems with a pass-through approach in terms of security, but in terms of ease-of-implementation, I think `inotify` is a huge beast...

**Comment by lead4good** [comment]
Thanks @dimakuv for the evaluation. It likes like running .NET with FileSystemWatcher on gramine is not worth it then.

**Comment by lead4good** [comment]
I've found a way around the inotify API by setting the  DOTNET_USE_POLLING_FILE_WATCHER env var which disables the FileSystemWatcher. This only works since .NET 5.0, as there is still a bug in the older dotnet-core runtime which tries to start the FileSystemWatcher even if the flag is set, see dotnet/runtime#41426.

**Comment by dimakuv** [comment]
Thanks @lead4good! We'll be happy if you'll be willing to contribute a simple .NET 5.0 example to the Gramine Examples repo: https://github.com/gramineproject/examples/.

I will close this issue now.

**Comment by lead4good** [comment]
@dimakuv I've developed a buildpack for gramine that sets up graminized applications in one command. There is still internal discussions regarding the license, but hopefully it will be open sourced and then I am happy to provide a buildpack example that showcases .NET!

**Comment by dimakuv** [comment]
@lead4good Just wanted to say it's a real pleasure to work with you!
