### ISSUE TITLE
Gramine doesn't emulate `/proc/stat` file

### ISSUE THREAD

**Issue by iqbaleric** [gramineproject/gramine#329]
I am seeing this error while running PyTorch. The application is not spawning over multiple threads as the CPUs stat are not accessible. 

shim_openat(AT_FDCWD,"/proc/stat",O_RDONLY|2000000,0000) = -2
FileNotFoundError: [Errno 2] No such file or directory: '/proc/stat'

**Comment by dimakuv** [comment]
I just found another workload that checks `/proc/stat`. The workload is Python's qiskit (https://qiskit.org/documentation/getting_started.html).

See https://github.com/gramineproject/gramine/pull/328 on how to test qiskit in our Python example. This is what happens when I run it:
```
gramine/CI-Examples/python$ gramine-sgx python scripts/example.py

Traceback (most recent call last):
  File "/home/dimakuv/.local/lib/python3.6/site-packages/psutil/_common.py", line 397, in wrapper
    return cache[key]
KeyError: (('/proc',), frozenset())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dimakuv/.local/lib/python3.6/site-packages/psutil/_pslinux.py", line 303, in <module>
    set_scputimes_ntuple("/proc")
  File "/home/dimakuv/.local/lib/python3.6/site-packages/psutil/_common.py", line 399, in wrapper
    ret = cache[key] = fun(*args, **kwargs)
  File "/home/dimakuv/.local/lib/python3.6/site-packages/psutil/_pslinux.py", line 270, in set_scputimes_ntuple
    with open_binary('%s/stat' % procfs_path) as f:
  File "/home/dimakuv/.local/lib/python3.6/site-packages/psutil/_common.py", line 711, in open_binary
    return open(fname, "rb", **kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/proc/stat'
/home/dimakuv/.local/lib/python3.6/site-packages/psutil/_pslinux.py:531: RuntimeWarning: buffers, cached, shared, active, inactive memory stats couldn't be determined and were set to 0
  warnings.warn(msg, RuntimeWarning)
/home/dimakuv/.local/lib/python3.6/site-packages/psutil/_pslinux.py:531: RuntimeWarning: buffers, cached, shared, active, inactive memory stats couldn't be determined and were set to 0
  warnings.warn(msg, RuntimeWarning)
```

To be more precise, two things happened here:
1. Python tried to open `/proc/stat` file and failed
2. Python tried to read from `/proc/cpuinfo` file some advances stats like `Buffers`, `Cached`, etc. and complained that it couldn't find these lines
