### ISSUE TITLE
The rust webserver rocket not working

### ISSUE THREAD

**Issue by kvinwang** [gramineproject/gramine#341]
## Description of the problem

I was trying to run the helloworld of the Rust webserver rocket with gramine-sgx and found it reject any incoming http request.

## Expected results
The helloworld just works fine.

## Actual results
Reject any incoming http request.

## Additional information
After looking into the source code, I found the cause is that Rocket webserver always set the socket's rw timeout with setsockopt and gramine does not support this function. Rocket reject to work after setting the timeout failed.

![image](https://user-images.githubusercontent.com/6442159/149706599-085637f8-1faa-419f-b77b-bf4771240df9.png)

**Comment by dimakuv** [comment]
I'm confused. You're talking about the Rust webserver rocket first, but the log that you show is from Nginx?

**Comment by kvinwang** [comment]
> I'm confused. You're talking about the Rust webserver rocket first, but the log that you show is from Nginx?

Sorry for the mislead. Actually, to be fast to setup, I reused the nginx example's Makefile and manifest. Just replaced the nginx binary with the rocket helloworld binary.

**Comment by dimakuv** [comment]
I see. Gramine actually supports `setsockopt(fd, SOL_SOCKET, SO_RCVTIMEO)` but looks like we have a small bug.

`SO_RCVTIMEO` and `SO_SNDTIMEO` (send/receive timeout values, see `man 7 socket`) are supposed to be of type `struct timeval` (16 bytes in size). However, in Gramine's PAL implementations we have them of type `int` (4 bytes in size). See these:
- https://github.com/gramineproject/gramine/blob/53d4f5c461d77b188523f8d80f3b146765967d3d/Pal/src/host/Linux/db_sockets.c#L1017
- https://github.com/gramineproject/gramine/blob/53d4f5c461d77b188523f8d80f3b146765967d3d/Pal/src/host/Linux/db_sockets.c#L1027
- https://github.com/gramineproject/gramine/blob/1202953d09af98fadb8b49b25b7b03c91458519a/Pal/src/host/Linux-SGX/db_sockets.c#L775
- https://github.com/gramineproject/gramine/blob/1202953d09af98fadb8b49b25b7b03c91458519a/Pal/src/host/Linux-SGX/db_sockets.c#L784

So looks like this is the source of the failure. We need to fix this and add a small regression test (or augment an existing regression test) to verify the bug fix.

**Comment by dimakuv** [comment]
We have the same issue in the LibOS component of Gramine. `SO_RCVTIMEO` and `SO_SNDTIMEO` are also treated as `int` values, which is wrong.

See: https://github.com/gramineproject/gramine/blob/53d4f5c461d77b188523f8d80f3b146765967d3d/LibOS/shim/src/sys/shim_socket.c#L1835-L1846

And: https://github.com/gramineproject/gramine/blob/53d4f5c461d77b188523f8d80f3b146765967d3d/LibOS/shim/src/sys/shim_socket.c#L2134-L2139

**Comment by jkr0103** [comment]
please assign to me

**Comment by jkr0103** [comment]
@kvinwang Could you please share the Makefile, manifest and binary file you have used to repro the issue?

**Comment by kvinwang** [comment]
Sure.
[gramine-build.tar.gz](https://github.com/gramineproject/gramine/files/8049651/gramine-build.tar.gz)

**Comment by jkr0103** [comment]
I am able to run your application `pruntime` in `gramine-sgx` mode with some config modifications in Makefile and manifest files. Also your application have requirement of minimum 512 `thread_num` and 8GB enclave size.
Could you extract the attached directory under gramine/CI-Examples and build/execute the application and let me know the results?
[pruntime.zip](https://github.com/gramineproject/gramine/files/8058845/pruntime.zip)

**Comment by kvinwang** [comment]
> Also your application have requirement of minimum 512 `thread_num` and 8GB enclave size.

Hmm, 32 threads is enough here.

> Could you extract the attached directory under gramine/CI-Examples and build/execute the application and let me know the results?

Sorry, I tried to make with your files and got an error:
```
Traceback (most recent call last):
  File "/home/kvin/.local/lib/python3.8/site-packages/toml/decoder.py", line 511, in loads
    ret = decoder.load_line(line, currentlevel, multikey,
  File "/home/kvin/.local/lib/python3.8/site-packages/toml/decoder.py", line 778, in load_line
    value, vtype = self.load_value(pair[1], strictly_valid)
  File "/home/kvin/.local/lib/python3.8/site-packages/toml/decoder.py", line 866, in load_value
    raise ValueError("Reserved escape sequence used")
ValueError: Reserved escape sequence used
```




> I am able to run your application `pruntime` in `gramine-sgx` mode with some config modifications in Makefile and manifest files

Yes, it is able to start and listening on local port 8001.  like this:
```
$ gramine-sgx pruntime
🔧 Configured for development.
    => address: localhost
    => port: 8001
    => log: normal
    => workers: 16
    => secret key: generated
    => limits: forms = 32KiB
    => keep-alive: 5s
    => read timeout: 5s
    => write timeout: 5s
    => tls: disabled
🛰  Mounting /:
    => GET /quit (quit)
🚀 Rocket has launched from http://localhost:8001
```

But if you run `curl http://localhost:8001` in anthor terminal, it will fail.
## Expected result
```
$ curl http://localhost:8001/

            <!DOCTYPE html>
            <html lang="en">
            <head>
                <meta charset="utf-8">
                <title>404 Not Found</title>
            </head>
            <body align="center">
                <div role="main" align="center">
                    <h1>404: Not Found</h1>
                    <p>The requested resource could not be found.</p>
                    <hr />
                </div>
                <div role="contentinfo" align="center">
                    <small>Rocket</small>
                </div>
            </body>
            </html>
```
## Actual result
```
$ curl http://localhost:8001/
curl: (56) Recv failure: Connection reset by peer
```

**Comment by dimakuv** [comment]
@kvinwang We just merged the bug fix for your issue. Please try to run your workload again on the latest Gramine.
