### ISSUE TITLE
fsync syscall permission denied

### ISSUE THREAD

**Issue by g302ge** [gramineproject/gramine#463]
## Description of the problem

These days, I am trying to play with rocksdb in gramine. But in my experimental code , I set the `sgx.allowed_files` manifest field in my manifest file. Unluckly, when I startup the project I got an error, which tell me I have no permission to call `fsync`. Maybe it is a bug of current version ? Thx for ur reply soon very much :)

## Steps to reproduce

1. git clone https://github.com/g302ge/gramocksdb.git
2. make all 
3. gramine-sgx gramocksdb

Or you can use directly with the binary gramocksdb, I have compiled it on ubuntu also commited in repo 

## Expected results

All test in `src/main.rs` pass, and the process return zero without any fault.

## Actual results

![image](https://user-images.githubusercontent.com/17953717/158751969-55aa95e0-8c00-4b5c-9c51-2eafef4b8b1b.png)

And the full log is below.

```
Parsing TOML manifest file, this may take some time...
warning: Parsed TOML manifest file successfully
debug: Token file: gramocksdb.token
debug: Read dummy DCAP token
debug: enclave created:
debug:     base:           0x0000000010000000
debug:     size:           0x0000000010000000
debug:     misc_select:    0x00000000
debug:     attr.flags:     0x0000000000000007
debug:     attr.xfrm:      0x0000000000000007
debug:     ssa_frame_size: 4
debug:     isv_prod_id:    0x00000000
debug:     isv_svn:        0x00000000
warning: Adding pages to SGX enclave, this may take some time...
debug: adding pages to enclave: 0x1fef7000-0x20000000 [REG:R--] (manifest) measured
debug: adding pages to enclave: 0x1fdf7000-0x1fef7000 [REG:RW-] (ssa) measured
debug: adding pages to enclave: 0x1fdd7000-0x1fdf7000 [TCS:---] (tcs) measured
debug: adding pages to enclave: 0x1fdb7000-0x1fdd7000 [REG:RW-] (tls) measured
debug: adding pages to enclave: 0x1fd77000-0x1fdb7000 [REG:RW-] (stack) measured
debug: adding pages to enclave: 0x1fd37000-0x1fd77000 [REG:RW-] (stack) measured
debug: adding pages to enclave: 0x1fcf7000-0x1fd37000 [REG:RW-] (stack) measured
debug: adding pages to enclave: 0x1fcb7000-0x1fcf7000 [REG:RW-] (stack) measured
debug: adding pages to enclave: 0x1fc77000-0x1fcb7000 [REG:RW-] (stack) measured
debug: adding pages to enclave: 0x1fc37000-0x1fc77000 [REG:RW-] (stack) measured
debug: adding pages to enclave: 0x1fbf7000-0x1fc37000 [REG:RW-] (stack) measured
debug: adding pages to enclave: 0x1fbb7000-0x1fbf7000 [REG:RW-] (stack) measured
debug: adding pages to enclave: 0x1fb77000-0x1fbb7000 [REG:RW-] (stack) measured
debug: adding pages to enclave: 0x1fb37000-0x1fb77000 [REG:RW-] (stack) measured
debug: adding pages to enclave: 0x1faf7000-0x1fb37000 [REG:RW-] (stack) measured
debug: adding pages to enclave: 0x1fab7000-0x1faf7000 [REG:RW-] (stack) measured
debug: adding pages to enclave: 0x1fa77000-0x1fab7000 [REG:RW-] (stack) measured
debug: adding pages to enclave: 0x1fa37000-0x1fa77000 [REG:RW-] (stack) measured
debug: adding pages to enclave: 0x1f9f7000-0x1fa37000 [REG:RW-] (stack) measured
debug: adding pages to enclave: 0x1f9b7000-0x1f9f7000 [REG:RW-] (stack) measured
debug: adding pages to enclave: 0x1f977000-0x1f9b7000 [REG:RW-] (stack) measured
debug: adding pages to enclave: 0x1f937000-0x1f977000 [REG:RW-] (stack) measured
debug: adding pages to enclave: 0x1f8f7000-0x1f937000 [REG:RW-] (stack) measured
debug: adding pages to enclave: 0x1f8b7000-0x1f8f7000 [REG:RW-] (stack) measured
debug: adding pages to enclave: 0x1f877000-0x1f8b7000 [REG:RW-] (stack) measured
debug: adding pages to enclave: 0x1f837000-0x1f877000 [REG:RW-] (stack) measured
debug: adding pages to enclave: 0x1f7f7000-0x1f837000 [REG:RW-] (stack) measured
debug: adding pages to enclave: 0x1f7b7000-0x1f7f7000 [REG:RW-] (stack) measured
debug: adding pages to enclave: 0x1f777000-0x1f7b7000 [REG:RW-] (stack) measured
debug: adding pages to enclave: 0x1f737000-0x1f777000 [REG:RW-] (stack) measured
debug: adding pages to enclave: 0x1f6f7000-0x1f737000 [REG:RW-] (stack) measured
debug: adding pages to enclave: 0x1f6b7000-0x1f6f7000 [REG:RW-] (stack) measured
debug: adding pages to enclave: 0x1f677000-0x1f6b7000 [REG:RW-] (stack) measured
debug: adding pages to enclave: 0x1f637000-0x1f677000 [REG:RW-] (stack) measured
debug: adding pages to enclave: 0x1f5f7000-0x1f637000 [REG:RW-] (stack) measured
debug: adding pages to enclave: 0x1f5b7000-0x1f5f7000 [REG:RW-] (stack) measured
debug: adding pages to enclave: 0x1f5a7000-0x1f5b7000 [REG:RW-] (sig_stack) measured
debug: adding pages to enclave: 0x1f597000-0x1f5a7000 [REG:RW-] (sig_stack) measured
debug: adding pages to enclave: 0x1f587000-0x1f597000 [REG:RW-] (sig_stack) measured
debug: adding pages to enclave: 0x1f577000-0x1f587000 [REG:RW-] (sig_stack) measured
debug: adding pages to enclave: 0x1f567000-0x1f577000 [REG:RW-] (sig_stack) measured
debug: adding pages to enclave: 0x1f557000-0x1f567000 [REG:RW-] (sig_stack) measured
debug: adding pages to enclave: 0x1f547000-0x1f557000 [REG:RW-] (sig_stack) measured
debug: adding pages to enclave: 0x1f537000-0x1f547000 [REG:RW-] (sig_stack) measured
debug: adding pages to enclave: 0x1f527000-0x1f537000 [REG:RW-] (sig_stack) measured
debug: adding pages to enclave: 0x1f517000-0x1f527000 [REG:RW-] (sig_stack) measured
debug: adding pages to enclave: 0x1f507000-0x1f517000 [REG:RW-] (sig_stack) measured
debug: adding pages to enclave: 0x1f4f7000-0x1f507000 [REG:RW-] (sig_stack) measured
debug: adding pages to enclave: 0x1f4e7000-0x1f4f7000 [REG:RW-] (sig_stack) measured
debug: adding pages to enclave: 0x1f4d7000-0x1f4e7000 [REG:RW-] (sig_stack) measured
debug: adding pages to enclave: 0x1f4c7000-0x1f4d7000 [REG:RW-] (sig_stack) measured
debug: adding pages to enclave: 0x1f4b7000-0x1f4c7000 [REG:RW-] (sig_stack) measured
debug: adding pages to enclave: 0x1f4a7000-0x1f4b7000 [REG:RW-] (sig_stack) measured
debug: adding pages to enclave: 0x1f497000-0x1f4a7000 [REG:RW-] (sig_stack) measured
debug: adding pages to enclave: 0x1f487000-0x1f497000 [REG:RW-] (sig_stack) measured
debug: adding pages to enclave: 0x1f477000-0x1f487000 [REG:RW-] (sig_stack) measured
debug: adding pages to enclave: 0x1f467000-0x1f477000 [REG:RW-] (sig_stack) measured
debug: adding pages to enclave: 0x1f457000-0x1f467000 [REG:RW-] (sig_stack) measured
debug: adding pages to enclave: 0x1f447000-0x1f457000 [REG:RW-] (sig_stack) measured
debug: adding pages to enclave: 0x1f437000-0x1f447000 [REG:RW-] (sig_stack) measured
debug: adding pages to enclave: 0x1f427000-0x1f437000 [REG:RW-] (sig_stack) measured
debug: adding pages to enclave: 0x1f417000-0x1f427000 [REG:RW-] (sig_stack) measured
debug: adding pages to enclave: 0x1f407000-0x1f417000 [REG:RW-] (sig_stack) measured
debug: adding pages to enclave: 0x1f3f7000-0x1f407000 [REG:RW-] (sig_stack) measured
debug: adding pages to enclave: 0x1f3e7000-0x1f3f7000 [REG:RW-] (sig_stack) measured
debug: adding pages to enclave: 0x1f3d7000-0x1f3e7000 [REG:RW-] (sig_stack) measured
debug: adding pages to enclave: 0x1f3c7000-0x1f3d7000 [REG:RW-] (sig_stack) measured
debug: adding pages to enclave: 0x1f3b7000-0x1f3c7000 [REG:RW-] (sig_stack) measured
debug: adding pages to enclave: 0x1ef7f000-0x1efdf000 [REG:R-X] (code) measured
debug: adding pages to enclave: 0x1efdf000-0x1efe3000 [REG:RW-] (data) measured
debug: adding pages to enclave: 0x1efe3000-0x1f3b7000 [REG:RW-] (bss) measured
debug: adding pages to enclave: 0x10000000-0x1ef7f000 [REG:RWX] (free)
warning: Added all pages to SGX enclave
debug: enclave initializing:
debug:     enclave id:   0x000000001ffff000
debug:     mr_enclave:   095e3999de6bad37bf22fa1f11b1382a3a4fa4458fd8040d71f39dbe5ddd39ed
-----------------------------------------------------------------------------------------------------------------------
Gramine detected the following insecure configurations:

  - sgx.debug = true                           (this is a debug enclave)
  - loader.log_level = warning|debug|trace|all (verbose log level, may leak information)
  - sgx.allowed_files = [ ... ]                (some files are passed through from untrusted host without verification)

Gramine will continue application execution, but this configuration must not be used in production!
-----------------------------------------------------------------------------------------------------------------------

warning: DkVirtualMemoryProtect is unimplemented in Linux-SGX PAL
[::] debug: Gramine was built from commit: 7846eccb5c226e9c6aa8775058d43506c6ad7cfd
[::] debug: Host: Linux-SGX
[::] debug: LibOS xsave_enabled 1, xsave_size 0x340(832), xsave_features 0x7
[::] debug: Initial VMA region 0x1e7b9000-0x1e865000 (LibOS) bookkeeped
[::] debug: Initial VMA region 0x1fef7000-0x20000000 (manifest) bookkeeped
[::] debug: ASLR top address adjusted to 0x17f6e000
[::] debug: Shim loaded at 0x1e7b9000, ready to initialize
[::] debug: mounting "file:." (chroot) under /
[::] debug: mounting "proc" (pseudo) under /proc
[::] debug: mounting "dev" (pseudo) under /dev
[::] debug: mounting "dev:tty" (chroot) under /dev/tty
[::] debug: Creating pipe: pipe.srv:5a7022954fdaf7e28b91395ae7f53c2a962f49a7cce8daf28aaac0828f3e167e
[P1:T1:] debug: mounting "file:/usr/local/lib/x86_64-linux-gnu/gramine/runtime/glibc" (chroot) under /lib
[P1:T1:] debug: mounting "file:/lib/x86_64-linux-gnu" (chroot) under /lib/x86_64-linux-gnu
[P1:T1:] debug: mounting "file:data" (chroot) under /data
[P1:T1:gramocksdb] debug: Creating pipe: pipe.srv:f8059bee67c92e13e1cb4b0451914da99e4333966e02a04a9127505da7af68ac
[P1:T1:gramocksdb] debug: Allocating stack at 0 (size = 262144)
[P1:T1:gramocksdb] debug: loading "file:./gramocksdb"
[P1:T1:gramocksdb] debug: append_r_debug: adding file:./gramocksdb at 0x179b7000
[P1:T1:gramocksdb] debug: find_interp: searching for interpreter: /lib/ld-linux-x86-64.so.2
[P1:T1:gramocksdb] debug: loading "file:/usr/local/lib/x86_64-linux-gnu/gramine/runtime/glibc/ld-linux-x86-64.so.2"
[P1:T1:gramocksdb] debug: append_r_debug: adding file:/usr/local/lib/x86_64-linux-gnu/gramine/runtime/glibc/ld-linux-x86-64.so.2 at 0x17983000
[P1:T1:gramocksdb] debug: Creating pipe: pipe.srv:1
[P1:T1:gramocksdb] debug: Creating pipe: pipe.srv:b39eda8b1d86e53d72d20754069afa7680262a50e440c0d2524c12819927389f
[P1:T1:gramocksdb] debug: Shim process initialized
[P1:shim] debug: IPC worker started
[P1:T1:gramocksdb] debug: append_r_debug: adding file:[vdso_libos] at 0x17982000
[P1:T1:gramocksdb] warning: Not supported flag (0x3001) passed to arch_prctl
[P1:T1:gramocksdb] debug: glibc register library /lib/x86_64-linux-gnu/libstdc++.so.6 loaded at 0x1779e000
[P1:T1:gramocksdb] debug: append_r_debug: adding file:/lib/x86_64-linux-gnu/libstdc++.so.6 at 0x1779e000
[P1:T1:gramocksdb] debug: glibc register library /lib/x86_64-linux-gnu/libgcc_s.so.1 loaded at 0x17783000
[P1:T1:gramocksdb] debug: append_r_debug: adding file:/lib/x86_64-linux-gnu/libgcc_s.so.1 at 0x17783000
[P1:T1:gramocksdb] debug: glibc register library /lib/libpthread.so.0 loaded at 0x1777e000
[P1:T1:gramocksdb] debug: append_r_debug: adding file:/usr/local/lib/x86_64-linux-gnu/gramine/runtime/glibc/libpthread.so.0 at 0x1777e000
[P1:T1:gramocksdb] debug: glibc register library /lib/libm.so.6 loaded at 0x176a3000
[P1:T1:gramocksdb] debug: append_r_debug: adding file:/usr/local/lib/x86_64-linux-gnu/gramine/runtime/glibc/libm.so.6 at 0x176a3000
[P1:T1:gramocksdb] debug: glibc register library /lib/libdl.so.2 loaded at 0x1769e000
[P1:T1:gramocksdb] debug: append_r_debug: adding file:/usr/local/lib/x86_64-linux-gnu/gramine/runtime/glibc/libdl.so.2 at 0x1769e000
[P1:T1:gramocksdb] debug: glibc register library /lib/libc.so.6 loaded at 0x174a4000
[P1:T1:gramocksdb] debug: append_r_debug: adding file:/usr/local/lib/x86_64-linux-gnu/gramine/runtime/glibc/libc.so.6 at 0x174a4000
[P1:T1:gramocksdb] warning: Unsupported system call 435
[P1:T1:gramocksdb] debug: Creating pipe: pipe.srv:4a83dc8a8c8c877ac8b6a79814b6746291188109ce892cc36324f9519781c076
[P1:T1:gramocksdb] warning: Unsupported system call 435
[P1:T1:gramocksdb] debug: Creating pipe: pipe.srv:8a1e6017c6c145e58fd618004bd2d25cae8dbf3d59218e9bdf2fced4f9eb592b
[P1:T3:gramocksdb] warning: Ignoring FUTEX_CLOCK_REALTIME flag
[P1:T1:gramocksdb] debug: statfs: 20000000 10000000 10000000
[P1:T1:gramocksdb] debug: statfs: 20000000 10000000 10000000
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { message: "IO error: While fsync: a directory: Permission denied" }', src/main.rs:21:41
stack backtrace:
[P1:T1:gramocksdb] warning: Unsupported system call statx
[P1:T1:gramocksdb] warning: Unsupported system call statx
[P1:T1:gramocksdb] warning: Unsupported system call statx
   0:         0x17e2665c - std::backtrace_rs::backtrace::libunwind::trace::h6ac5130eed1dcf9f
                               at /rustc/1eb72580d076935a3e590deb6e5813a5aef3eca4/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:         0x17e2665c - std::backtrace_rs::backtrace::trace_unsynchronized::h2b7158a3e8f3af61
                               at /rustc/1eb72580d076935a3e590deb6e5813a5aef3eca4/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:         0x17e2665c - std::sys_common::backtrace::_print_fmt::h75f85af0fdb05879
                               at /rustc/1eb72580d076935a3e590deb6e5813a5aef3eca4/library/std/src/sys_common/backtrace.rs:66:5
   3:         0x17e2665c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h5f37961d0a32553a
                               at /rustc/1eb72580d076935a3e590deb6e5813a5aef3eca4/library/std/src/sys_common/backtrace.rs:45:22
   4:         0x17e40bec - core::fmt::write::h29046f193433d2f3
                               at /rustc/1eb72580d076935a3e590deb6e5813a5aef3eca4/library/core/src/fmt/mod.rs:1190:17
   5:         0x17e23d71 - std::io::Write::write_fmt::h85f676fd3a2afd23
                               at /rustc/1eb72580d076935a3e590deb6e5813a5aef3eca4/library/std/src/io/mod.rs:1655:15
   6:         0x17e27d85 - std::sys_common::backtrace::_print::h79369394439142a7
                               at /rustc/1eb72580d076935a3e590deb6e5813a5aef3eca4/library/std/src/sys_common/backtrace.rs:48:5
   7:         0x17e27d85 - std::sys_common::backtrace::print::h358c3300488d298b
                               at /rustc/1eb72580d076935a3e590deb6e5813a5aef3eca4/library/std/src/sys_common/backtrace.rs:35:9
   8:         0x17e27d85 - std::panicking::default_hook::{{closure}}::hbbc54c317f78453b
                               at /rustc/1eb72580d076935a3e590deb6e5813a5aef3eca4/library/std/src/panicking.rs:295:22
   9:         0x17e27a28 - std::panicking::default_hook::he69a91523cadf6a8
                               at /rustc/1eb72580d076935a3e590deb6e5813a5aef3eca4/library/std/src/panicking.rs:314:9
  10:         0x17e282d3 - std::panicking::rust_panic_with_hook::h88c443d0811b5ee8
                               at /rustc/1eb72580d076935a3e590deb6e5813a5aef3eca4/library/std/src/panicking.rs:698:17
  11:         0x17e281b7 - std::panicking::begin_panic_handler::{{closure}}::hf0e3adb08d6f840d
                               at /rustc/1eb72580d076935a3e590deb6e5813a5aef3eca4/library/std/src/panicking.rs:588:13
  12:         0x17e26b14 - std::sys_common::backtrace::__rust_end_short_backtrace::h876fe414bbc74075
                               at /rustc/1eb72580d076935a3e590deb6e5813a5aef3eca4/library/std/src/sys_common/backtrace.rs:138:18
  13:         0x17e27ee9 - rust_begin_unwind
                               at /rustc/1eb72580d076935a3e590deb6e5813a5aef3eca4/library/std/src/panicking.rs:584:5
  14:         0x17a20803 - core::panicking::panic_fmt::hb2c11159edd998a3
                               at /rustc/1eb72580d076935a3e590deb6e5813a5aef3eca4/library/core/src/panicking.rs:143:14
  15:         0x17a20893 - core::result::unwrap_failed::hd4f8fd644547ed9d
                               at /rustc/1eb72580d076935a3e590deb6e5813a5aef3eca4/library/core/src/result.rs:1784:5
  16:         0x17a46107 - gramocksdb::main::hafadb54f93c61bbe
  17:         0x17a421a3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h12305c5f0abd0220
  18:         0x17a479d9 - std::rt::lang_start::{{closure}}::h4f07c4ee2a79d224
  19:         0x17e25deb - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hb45fb6e5d6b3737a
                               at /rustc/1eb72580d076935a3e590deb6e5813a5aef3eca4/library/core/src/ops/function.rs:259:13
  20:         0x17e25deb - std::panicking::try::do_call::he5037ad1eb203c16
                               at /rustc/1eb72580d076935a3e590deb6e5813a5aef3eca4/library/std/src/panicking.rs:492:40
  21:         0x17e25deb - std::panicking::try::h2a41162a6dbb922a
                               at /rustc/1eb72580d076935a3e590deb6e5813a5aef3eca4/library/std/src/panicking.rs:456:19
  22:         0x17e25deb - std::panic::catch_unwind::h7ba3515aecd46d8e
                               at /rustc/1eb72580d076935a3e590deb6e5813a5aef3eca4/library/std/src/panic.rs:137:14
  23:         0x17e25deb - std::rt::lang_start_internal::{{closure}}::h42b423f0d606139d
                               at /rustc/1eb72580d076935a3e590deb6e5813a5aef3eca4/library/std/src/rt.rs:128:48
  24:         0x17e25deb - std::panicking::try::do_call::hc070550b805bf778
                               at /rustc/1eb72580d076935a3e590deb6e5813a5aef3eca4/library/std/src/panicking.rs:492:40
  25:         0x17e25deb - std::panicking::try::heb8a086d3eda308a
                               at /rustc/1eb72580d076935a3e590deb6e5813a5aef3eca4/library/std/src/panicking.rs:456:19
  26:         0x17e25deb - std::panic::catch_unwind::h36cd43754cc229ee
                               at /rustc/1eb72580d076935a3e590deb6e5813a5aef3eca4/library/std/src/panic.rs:137:14
  27:         0x17e25deb - std::rt::lang_start_internal::h8d843bd59d61a4e9
                               at /rustc/1eb72580d076935a3e590deb6e5813a5aef3eca4/library/std/src/rt.rs:128:20
  28:         0x17a46972 - main
[P1:T1:gramocksdb] warning: Unsupported system call statx
[P1:T2:gramocksdb] warning: Ignoring FUTEX_CLOCK_REALTIME flag
[P1:T1:gramocksdb] warning: Unsupported system call mremap
  29:         0x174d14ed - __libc_start_call_main
                               at /home/george/devlop/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  30:         0x174d15ac - __libc_start_main_impl
                               at /home/george/devlop/gramine/build/subprojects/glibc-2.34-1/crt1.o.p/csu/../csu/libc-start.c:409:3
  31:         0x17a411ee - _start
  32:                0x0 - <unknown>
[P1:T2:gramocksdb] debug: ---- shim_exit (returning 0)
[P1:T1:gramocksdb] warning: Ignoring FUTEX_CLOCK_REALTIME flag
[P1:T1:gramocksdb] warning: Non-private futexes are not supported, assuming implicit FUTEX_PRIVATE_FLAG
[P1:T2:gramocksdb] debug: Creating pipe: pipe.srv:47f9b5a145f4782a55958d3b087db1989718bd17dc3ba07ad31f800f0c62f1c5
[P1:shim] debug: Async worker thread started
[P1:T2:gramocksdb] debug: Installed async event at 1647499371836313
[P1:shim] debug: Thread exited, cleaning up
[P1:T1:gramocksdb] warning: Ignoring FUTEX_CLOCK_REALTIME flag
[P1:T1:gramocksdb] warning: Non-private futexes are not supported, assuming implicit FUTEX_PRIVATE_FLAG
[P1:T3:gramocksdb] debug: ---- shim_exit (returning 0)
[P1:T3:gramocksdb] debug: Installed async event at 1647499371839897
[P1:shim] debug: Thread exited, cleaning up
[P1:T1:gramocksdb] debug: ---- shim_exit_group (returning 101)
[P1:T1:gramocksdb] debug: clearing POSIX locks for pid 1
[P1:T1:gramocksdb] debug: sync client shutdown: closing handles
[P1:T1:gramocksdb] debug: sync client shutdown: waiting for confirmation
[P1:T1:gramocksdb] debug: sync client shutdown: finished
[P1:shim] debug: Async worker thread terminated
[P1:shim] debug: IPC worker: exiting worker thread
[P1:T1:gramocksdb] debug: process 1 exited with status 101
debug: DkProcessExit: Returning exit code 101

```

## Gramine commit hash

7846eccb5c226e9c6aa8775058d43506c6ad7cfd

**Comment by dimakuv** [comment]
The `fsync()` system call is implemented and fully supported in Gramine: https://github.com/gramineproject/gramine/blob/0f9b650deded24998e645029c7379d142ae78c0a/LibOS/shim/src/sys/shim_open.c#L461

The problem seems to be in something else. Could you provide us with more details:
1. Please copy/attach your `manifest.template` file
2. Please set `loader.log_level = "all"` in your manifest template file, rebuild and rerun and copy/attach the resulting log

This will give us enough information to analyze what exactly is breaking and why.

**Comment by g302ge** [comment]
Thx for replay, and here is my manifest file 

```
[libos]
entrypoint = "gramocksdb" 

[loader]
preload = "file:{{ gramine.libos }}"
entrypoint = "file:{{ gramine.libos }}"
log_level = "{{ log_level }}"
argv0_override = "gramocksdb"
insecure_use_cmdline_argv = true 

[loader.env]
LD_LIBRARY_PATH = "/lib:/lib/x86_64-linux-gnu"
#M_ARENA_MAX = "1"
RUST_BACKTRACE = "full"

[fs]
mounts = [
    { type = "chroot", path = "/lib", uri = "file:{{ gramine.runtimedir() }}" },
    { type = "chroot", path = "/lib/x86_64-linux-gnu", uri = "file:/lib/x86_64-linux-gnu" },
    { type = "chroot", path = "/data", uri = "file:data" },
]

[sgx]
debug = true
encalve_size = "2G"
thread_num = 32
trusted_files = [
    "file:{{ gramine.libos }}",
    "file:{{ gramine.runtimedir() }}/",
    "file:gramocksdb",
    "file:/lib/x86_64-linux-gnu/",
]
allowed_files = [
    "file:data/",
]
#protected_mrenclave_files = [
#    "file:data/"
#]
```

**Comment by g302ge** [comment]
And the full log file is https://github.com/g302ge/gramocksdb/blob/main/rdb.log

**Comment by dimakuv** [comment]
> `encalve_size = "2G"`

Quick comment: you have a typo here. It should be `enclave_size`.

**Comment by dimakuv** [comment]
Thanks for the provided info. Now I see the issue in Gramine.

This is where it fails: https://github.com/g302ge/gramocksdb/blob/main/rdb.log#L692

Indeed, it is a problem with `fsync()`, it returns `-13` = `-EACCES`.

These are the offending lines in Gramine: https://github.com/gramineproject/gramine/blob/0f9b650deded24998e645029c7379d142ae78c0a/LibOS/shim/src/sys/shim_open.c#L472-L473

So currently Gramine doesn't handle `fsync()` on the directory FD. Looking through `git blame`, we always had this limitation. Apparently, apps do this (fsync on a directory) so rarely that we never hit this limitation.

@pwmarcz @mkow Any ideas on a quick fix for this? Removing these two lines would just work, or it's more complicated than this?

**Comment by g302ge** [comment]
Thx for ur replay very much, I fix the typo firstly

**Comment by pwmarcz** [comment]
@dimakuv I would even explictly make it a no-op: return 0 without calling the underlying `flush` operation. Gramine's systems don't do anything meaningful when you flush a directory, and may not expect it.

**Comment by dimakuv** [comment]
@pwmarcz Let me cook a quick PR with this. I'll ask you to review it.

**Comment by dimakuv** [comment]
@g302ge Could you check if https://github.com/gramineproject/gramine/pull/464 fixes this problem for you?

**Comment by g302ge** [comment]
Thx very much, It works correctly. Thx again
