### ISSUE TITLE
graminelibos.manifest.ManifestError: Cannot resolve /usr/lib/x86_64-linux-gnu/gramine/libsysdb.so

### ISSUE THREAD

**Issue by aep** [gramineproject/gramine#484]
## Description of the problem

it appears the default install location is /usr/local but the manifests point to /usr

so this doesnt work https://gramine.readthedocs.io/en/latest/quickstart.html

since according to https://github.com/gramineproject/gramine/issues/454#issuecomment-1064841443
we're supposed to install from git, not packages

```
git clone https://github.com/gramineproject/gramine.git
cd gramine
meson setup build/ --buildtype=release -Ddirect=enabled -Dsgx=enabled
ninja -C build/
sudo ninja -C build/ install
cd CI-Examples/helloworld
make SGX=1


root@hma3:~/gramine/CI-Examples/helloworld# make SGX=1
gramine-sgx-sign \
	--manifest helloworld.manifest \
	--output helloworld.manifest.sgx
Traceback (most recent call last):
  File "/usr/local/bin/gramine-sgx-sign", line 74, in <module>
    main() # pylint: disable=no-value-for-parameter
  File "/usr/lib/python3/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/bin/gramine-sgx-sign", line 34, in main
    expanded = manifest.expand_all_trusted_files()
  File "/usr/local/lib/python3.9/dist-packages/graminelibos/manifest.py", line 174, in expand_all_trusted_files
    append_trusted_dir_or_file(trusted_files, tf, expanded)
  File "/usr/local/lib/python3.9/dist-packages/graminelibos/manifest.py", line 55, in append_trusted_dir_or_file
    raise ManifestError(f'Cannot resolve {path}')
graminelibos.manifest.ManifestError: Cannot resolve /usr/lib/x86_64-linux-gnu/gramine/libsysdb.so
make: *** [Makefile:27: helloworld.manifest.sgx] Error 1

```

## Gramine commit hash

e37f773d4d910799a854b90334f2ff8eb6f411bd

**Comment by aep** [comment]
> Just some explanations. 

thanks, this helps. in this case i think what happened is that i first built it using the distro package, then installed from git but the manifests aren't regenerated from template. this is a side corner case that should go away when we only need a single install source.
