### ISSUE TITLE
`SECRET_PROVISION_SECRET_STRING` not set in enclave

### ISSUE THREAD

**Issue by mcapuccini** [gramineproject/gramine#491]
## Description of the problem
Hello! I am trying to provision a secret string in a python application using the high-level EPID attestation. I have written a C++ provisioning server that looks like this.

```cpp
// server.cpp
#include <iostream>

extern "C" {
#include "secret_prov.h"
}

int main(int argc, char** argv) {
  std::string secret = "mysecret";
  size_t secret_size = secret.size();
  std::cerr << "Secret: " << secret << std::endl;
  std::cerr << "Size: " << secret_size << std::endl;
  secret_provision_start_server((uint8_t*)secret.c_str(), secret_size, "4433",
                                "certs/server.crt", "certs/server.key", NULL,
                                NULL);
}
```

When running `gramine-sgx python -c 'import os; print(os.environ["SECRET_PROVISION_SECRET_STRING"])'` I get the following output.

```
debug: Token file: python.token
debug: Read dummy DCAP token
debug: enclave created:
debug:     base:           0x0000000000000000
debug:     size:           0x0000000010000000
debug:     misc_select:    0x00000000
debug:     attr.flags:     0x0000000000000007
debug:     attr.xfrm:      0x0000000000000007
debug:     ssa_frame_size: 4
debug:     isv_prod_id:    0x00000000
debug:     isv_svn:        0x00000000
debug: adding pages to enclave: 0xffb2000-0x10000000 [REG:R--] (manifest) measured
debug: adding pages to enclave: 0xff72000-0xffb2000 [REG:RW-] (ssa) measured
debug: adding pages to enclave: 0xff6a000-0xff72000 [TCS:---] (tcs) measured
debug: adding pages to enclave: 0xff62000-0xff6a000 [REG:RW-] (tls) measured
debug: adding pages to enclave: 0xff22000-0xff62000 [REG:RW-] (stack) measured
debug: adding pages to enclave: 0xfee2000-0xff22000 [REG:RW-] (stack) measured
debug: adding pages to enclave: 0xfea2000-0xfee2000 [REG:RW-] (stack) measured
debug: adding pages to enclave: 0xfe62000-0xfea2000 [REG:RW-] (stack) measured
debug: adding pages to enclave: 0xfe22000-0xfe62000 [REG:RW-] (stack) measured
debug: adding pages to enclave: 0xfde2000-0xfe22000 [REG:RW-] (stack) measured
debug: adding pages to enclave: 0xfda2000-0xfde2000 [REG:RW-] (stack) measured
debug: adding pages to enclave: 0xfd62000-0xfda2000 [REG:RW-] (stack) measured
debug: adding pages to enclave: 0xfd52000-0xfd62000 [REG:RW-] (sig_stack) measured
debug: adding pages to enclave: 0xfd42000-0xfd52000 [REG:RW-] (sig_stack) measured
debug: adding pages to enclave: 0xfd32000-0xfd42000 [REG:RW-] (sig_stack) measured
debug: adding pages to enclave: 0xfd22000-0xfd32000 [REG:RW-] (sig_stack) measured
debug: adding pages to enclave: 0xfd12000-0xfd22000 [REG:RW-] (sig_stack) measured
debug: adding pages to enclave: 0xfd02000-0xfd12000 [REG:RW-] (sig_stack) measured
debug: adding pages to enclave: 0xfcf2000-0xfd02000 [REG:RW-] (sig_stack) measured
debug: adding pages to enclave: 0xfce2000-0xfcf2000 [REG:RW-] (sig_stack) measured
debug: adding pages to enclave: 0xf8be000-0xf90a000 [REG:R-X] (code) measured
debug: adding pages to enclave: 0xf90a000-0xf90e000 [REG:RW-] (data) measured
debug: adding pages to enclave: 0xf90e000-0xfce2000 [REG:RW-] (bss) measured
debug: adding pages to enclave: 0x10000-0xf8be000 [REG:RWX] (free)
debug: enclave initializing:
debug:     enclave id:   xxxx
debug:     mr_enclave:   xxxx
debug: Using SGX EPID attestation
-----------------------------------------------------------------------------------------------------------------------
Gramine detected the following insecure configurations:

  - sgx.debug = true                           (this is a debug enclave)
  - loader.log_level = warning|debug|trace|all (verbose log level, may leak information)
  - loader.insecure__use_cmdline_argv = true   (forwarding command-line args from untrusted host to the app)
  - loader.insecure__use_host_env = true       (forwarding environment vars from untrusted host to the app)
  - sgx.allowed_files = [ ... ]                (some files are passed through from untrusted host without verification)

Gramine will continue application execution, but this configuration must not be used in production!
-----------------------------------------------------------------------------------------------------------------------

warning: DkVirtualMemoryProtect is unimplemented in Linux-SGX PAL
[::] debug: Gramine was built from commit: 3623e6322f0e652cb4757be5d037295e3ac7fa95
[::] debug: Host: Linux-SGX
[::] debug: LibOS xsave_enabled 1, xsave_size 0x340(832), xsave_features 0x7
[::] debug: Initial VMA region 0xf611000-0xf68d000 (LibOS) bookkeeped
[::] debug: Initial VMA region 0xffb2000-0x10000000 (manifest) bookkeeped
[::] debug: ASLR top address adjusted to 0x4d11000
[::] debug: Shim loaded at 0xf611000, ready to initialize
[::] debug: Mounting root as chroot filesystem: from file:. to /
[::] debug: Mounting special proc filesystem: /proc
[::] debug: Mounting special dev filesystem: /dev
[::] debug: Mounting terminal device /dev/tty under /dev
[::] debug: Creating pipe: pipe.srv:8481b27e080d174b8c51a09ee3dc39689554666b5322cdde801dc5a9be520180
[P1:T1:] debug: Mounting as chroot filesystem: from file:/opt/conda/envs/default/lib/x86_64-linux-gnu/gramine/runtime/glibc to /lib
[P1:T1:] debug: Mounting as chroot filesystem: from file:/tmp to /tmp
[P1:T1:] debug: Mounting as chroot filesystem: from file:/etc/ to /etc
[P1:T1:] debug: Mounting as chroot filesystem: from file:/app/config to /app/config
[P1:T1:] debug: Mounting as chroot filesystem: from file:/lib/x86_64-linux-gnu to /lib/x86_64-linux-gnu
[P1:T1:] debug: Mounting as chroot filesystem: from file:/opt/conda/envs/default to /opt/conda/envs/default
[P1:T1:] debug: Mounting as chroot filesystem: from file:/usr/lib/x86_64-linux-gnu to /usr/lib/x86_64-linux-gnu
[P1:T1:python3.8] debug: Creating pipe: pipe.srv:ca64f9379201f9cac2de7964627d66981179abbba56e4a3e0822d8626f00e397
[P1:T1:python3.8] debug: Allocating stack at 0 (size = 262144)
[P1:T1:python3.8] debug: loading "file:/opt/conda/envs/default/bin/python3.8"
[P1:T1:python3.8] debug: find_interp: searching for interpreter: /lib/ld-linux-x86-64.so.2
[P1:T1:python3.8] debug: loading "file:/opt/conda/envs/default/lib/x86_64-linux-gnu/gramine/runtime/glibc/ld-linux-x86-64.so.2"
[P1:T1:python3.8] debug: Creating pipe: pipe.srv:1
[P1:T1:python3.8] debug: Creating pipe: pipe.srv:3509521da4220b713dc620e3a0588f48be08bd8a6e10fa391e56517fee82ab6b
[P1:T1:python3.8] debug: Shim process initialized
[P1:shim] debug: IPC worker started
[P1:T1:python3.8] debug: glibc register library /lib/libsecret_prov_attest.so loaded at 0x04903000
[P1:T1:python3.8] debug: glibc register library /lib/libpthread.so.0 loaded at 0x048fe000
[P1:T1:python3.8] debug: glibc register library /lib/libdl.so.2 loaded at 0x048f9000
[P1:T1:python3.8] debug: glibc register library /lib/libutil.so.1 loaded at 0x048f4000
[P1:T1:python3.8] debug: glibc register library /lib/librt.so.1 loaded at 0x048ef000
[P1:T1:python3.8] debug: glibc register library /lib/libm.so.6 loaded at 0x04815000
[P1:T1:python3.8] debug: glibc register library /lib/libc.so.6 loaded at 0x04621000
[P1:T1:python3.8] debug: glibc register library /lib/libmbedcrypto_gramine.so.6 loaded at 0x045b0000
[P1:T1:python3.8] debug: glibc register library /lib/libmbedtls_gramine.so.13 loaded at 0x04580000
[P1:T1:python3.8] debug: glibc register library /lib/libmbedx509_gramine.so.1 loaded at 0x04560000
[P1:T1:python3.8] debug: glibc register library /opt/conda/envs/default/lib/python3.8/lib-dynload/_heapq.cpython-38-x86_64-linux-gnu.so loaded at 0x04095000
********************************************************************
*** Secret Provisioning library detected mbedTLS test certificates *
*** loaded into it. If this is a production system, please         *
*** terminate this application.                                    *
********************************************************************
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/envs/default/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'SECRET_PROVISION_SECRET_STRING'
[P1:T1:python3.8] debug: ---- shim_exit_group (returning 1)
[P1:T1:python3.8] debug: clearing POSIX locks for pid 1
[P1:T1:python3.8] debug: sync client shutdown: closing handles
[P1:T1:python3.8] debug: sync client shutdown: waiting for confirmation
[P1:T1:python3.8] debug: sync client shutdown: finished
[P1:shim] debug: IPC worker: exiting worker thread
[P1:T1:python3.8] debug: process 1 exited with status 1
debug: DkProcessExit: Returning exit code 1
```

Note that I get `KeyError: 'SECRET_PROVISION_SECRET_STRING'` meaning that `SECRET_PROVISION_SECRET_STRING` was not set in the environment.

On server side I get the following output:

```
Secret: mysecret
Size: 8
********************************************************************
*** Secret Provisioning library detected mbedTLS test certificates *
*** loaded into it. If this is a production system, please         *
*** terminate this application.                                    *
********************************************************************
IAS report: signature verified correctly
IAS report: quote status OK
```

Something is happening but the string is not provisioned in the enclave. What am I missing? I thought that by passing NULL as callback some default logic would be triggered but perhaps this is not the case? Thanks in advance!

## Steps to reproduce
Look at the description. Some additional details follow.

```
# python.manifest.template
loader.preload = "file:{{ gramine.libos }}"
loader.entrypoint = "file:{{ gramine.libos }}"
libos.entrypoint = "{{ entrypoint }}"
loader.log_level = "{{ log_level }}"
loader.env.LD_LIBRARY_PATH = "/lib:/usr/lib:/usr/lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu"
loader.insecure__use_cmdline_argv = true
loader.insecure__use_host_env = true
loader.argv0_override = "{{ entrypoint }}"
loader.env.LD_PRELOAD = "libsecret_prov_attest.so"
loader.env.SECRET_PROVISION_CONSTRUCTOR = "1"
loader.env.SECRET_PROVISION_CA_CHAIN_PATH = "certs/client.crt"

fs.mount.lib.type = "chroot"
fs.mount.lib.path = "/lib"
fs.mount.lib.uri = "file:{{ gramine.runtimedir() }}"

fs.mount.lib2.type = "chroot"
fs.mount.lib2.path = "/usr/lib/x86_64-linux-gnu"
fs.mount.lib2.uri = "file:/usr/lib/x86_64-linux-gnu"

fs.mount.lib3.type = "chroot"
fs.mount.lib3.path = "/lib/x86_64-linux-gnu"
fs.mount.lib3.uri = "file:/lib/x86_64-linux-gnu"

fs.mount.env_home.type = "chroot"
fs.mount.env_home.path = "{{ env_home }}"
fs.mount.env_home.uri = "file:{{ env_home }}"

fs.mount.tmp.type = "chroot"
fs.mount.tmp.path = "/tmp"
fs.mount.tmp.uri = "file:/tmp"

fs.mount.config.type = "chroot"
fs.mount.config.path = "/app/config"
fs.mount.config.uri = "file:/app/config"

fs.mount.etc.type = "chroot"
fs.mount.etc.path = "/etc"
fs.mount.etc.uri = "file:/etc/"

sgx.thread_num = 8
sgx.debug = true
sgx.nonpie_binary = true
sgx.ra_client_spid = "{{ ra_client_spid }}"
sgx.ra_client_linkable = {{ 'true' if ra_client_linkable == '1' else 'false' }}
sgx.remote_attestation = true

sgx.allowed_files = [
    "file:/tmp/",
    "file:{{ env_home }}/",
    "file:/etc/nsswitch.conf",
    "file:/etc/host.conf",
    "file:/etc/hosts",
    "file:/etc/group",
    "file:/etc/passwd",
    "file:/etc/gai.conf",
    "file:/etc/resolv.conf",
]

sgx.trusted_files = [
    "file:{{ gramine.libos }}",
    "file:{{ entrypoint }}",
    "file:{{ gramine.runtimedir() }}/",
    "file:/usr/lib/x86_64-linux-gnu/",
    "file:/lib/x86_64-linux-gnu/",
    "file:certs/client.crt",
]
```

```
# CMakeLists.txt
# Project
cmake_minimum_required(VERSION 3.0 FATAL_ERROR)
project(attestation)

# Mongo
find_package(libmongocxx REQUIRED)
include_directories(${LIBMONGOCXX_INCLUDE_DIR})
include_directories("/usr/local/include/mongocxx/v_noabi")
include_directories("/usr/local/include/bsoncxx/v_noabi")

# Gramine
include_directories("/opt/gramine/Pal/src/host/Linux-SGX/tools/ra-tls")
link_directories("/opt/conda/envs/default/lib/x86_64-linux-gnu")

# Executable
add_executable(server "server.cpp")
target_link_libraries(server ${LIBMONGOCXX_LIBRARIES})
target_link_libraries(server secret_prov_verify_epid)
```

I am running in a Docker container that was built as it follows.

```Dockerfile
# Base image
FROM debian:bookworm

# Env versioning
ARG HADOLINT_VERSION=v2.8.0
ARG CMAKE_VERSION=3.16.9
ARG DOCKER_VERSION=19.03.9
ARG CONDA_VERSION=4.9.2
ARG COMPOSE_VERSION=1.29.2
ARG SGX_SDK_VERSION=2.15.101.1
ARG SGX_PSW_VERSION=2.15.1
ARG GRAMINE_HEAD=v1.1
ARG MONGO_VERSION=3.6.6

# Non-root user with sudo access
ARG USERNAME=default
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Avoid warnings by switching to noninteractive
ENV DEBIAN_FRONTEND=noninteractive

# Other env
ENV TORCH_DIR=/opt/torch
ENV DATA_DIR=/app/data

# Install apt deps
SHELL ["/bin/bash", "-c"]
RUN apt-get update \
  && apt-get -y install --no-install-recommends \
  apt-utils \
  dialog 2>&1 \
  #
  # More apt deps
  && apt-get install -y --no-install-recommends \
  sudo \
  ca-certificates \
  wget \
  curl \
  git \
  vim \
  openssh-client \
  build-essential \
  autoconf \
  libtool \
  pkg-config \
  googletest \
  libgtest-dev \
  autoconf \
  gawk \
  libcurl4-openssl-dev \
  libprotobuf-c-dev \
  protobuf-c-compiler \
  linux-headers-amd64 \
  unzip \
  bison \
  libmongoc-dev \
  #
  # Hadolint
  && wget --progress=dot:giga -O /bin/hadolint \
  https://github.com/hadolint/hadolint/releases/download/${HADOLINT_VERSION}/hadolint-Linux-x86_64 \
  && chmod +x /bin/hadolint \
  #
  # Install docker binaries
  && curl -L https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKER_VERSION}.tgz | tar xvz docker/docker \
  && cp docker/docker /usr/local/bin \
  && rm -R docker \
  && curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose \
  && chmod +x /usr/local/bin/docker-compose \
  #
  # Install cmake
  && wget -q -O cmake-linux.sh https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-Linux-x86_64.sh \
  && sh cmake-linux.sh -- --skip-license \
  && rm cmake-linux.sh \
  #
  # SGX SDK
  && wget --progress=dot:giga https://download.01.org/intel-sgx/latest/linux-latest/distro/ubuntu20.04-server/sgx_linux_x64_sdk_${SGX_SDK_VERSION}.bin \
  && chmod +x sgx_linux_x64_sdk_${SGX_SDK_VERSION}.bin \
  && ./sgx_linux_x64_sdk_${SGX_SDK_VERSION}.bin --prefix /opt/sgx-sdk \
  && rm sgx_linux_x64_sdk_${SGX_SDK_VERSION}.bin \
  #
  # SGX PSW
  && wget --progress=dot:giga https://download.01.org/intel-sgx/sgx-linux/${SGX_PSW_VERSION}/distro/ubuntu20.04-server/sgx_debian_local_repo.tgz \
  && tar xzvf sgx_debian_local_repo.tgz \
  && mv sgx_debian_local_repo /opt \
  && echo 'deb [trusted=yes] file:///opt/sgx_debian_local_repo focal main' >> /etc/apt/sources.list \
  && echo 'deb [trusted=yes] http://archive.ubuntu.com/ubuntu focal main' >> /etc/apt/sources.list \
  && apt-get update \
  && sudo apt-get install -y --no-install-recommends \
  ubuntu-keyring \
  libsgx-urts \
  libsgx-launch \
  libsgx-epid \
  libsgx-quote-ex \
  libsgx-dcap-ql \
  #
  # Mongo CXX
  && wget --progress=dot:giga https://github.com/mongodb/mongo-cxx-driver/releases/download/r${MONGO_VERSION}/mongo-cxx-driver-r${MONGO_VERSION}.tar.gz \
  && tar -xzf mongo-cxx-driver-r${MONGO_VERSION}.tar.gz \
  && pushd mongo-cxx-driver-r${MONGO_VERSION}/build \
  && cmake .. -DCMAKE_BUILD_TYPE=Release  -DCMAKE_INSTALL_PREFIX=/usr/local \
  && cmake --build . --target EP_mnmlstc_core \
  && cmake --build . \
  && cmake --build . --target install \
  && popd \
  && rm mongo-cxx-driver-r${MONGO_VERSION}.tar.gz \
  && rm -r mongo-cxx-driver-r${MONGO_VERSION} \
  # 
  # Install conda
  && wget --progress=dot:giga https://repo.anaconda.com/miniconda/Miniconda3-py39_${CONDA_VERSION}-Linux-x86_64.sh \
  && bash Miniconda3-py39_${CONDA_VERSION}-Linux-x86_64.sh -b -p /opt/conda \
  && rm -f Miniconda3-py39_${CONDA_VERSION}-Linux-x86_64.sh \
  && ln -s /opt/conda/bin/conda /bin/conda \
  && ln -s /opt/conda/bin/conda-env /bin/conda-env \
  #
  # Create a non-root user to use if preferred
  && groupadd --gid $USER_GID $USERNAME \
  && useradd -s /bin/bash --uid $USER_UID --gid $USER_GID -m $USERNAME \
  && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
  && chmod 0440 /etc/sudoers.d/$USERNAME \
  #
  # Configure FEDn directories
  && mkdir -p /app/certs \
  && mkdir -p /app/client/package \
  && mkdir -p /app/config \
  && chown -R $USERNAME /app \
  #
  # Configure data dir
  && mkdir -p $DATA_DIR \
  && chown $USERNAME $DATA_DIR \
  #
  # Configure for gramine
  && mkdir -p /usr/include/asm \
  && ln -s /usr/src/linux-headers-*/arch/x86/include/uapi/asm/sgx.h /usr/include/asm/sgx.h \
  && mkdir -p /opt/gramine \
  && chown -R $USERNAME /opt/gramine \
  #
  # Cleanup
  && apt-get autoremove -y \
  && apt-get clean -y \
  && rm -rf /var/lib/apt/lists/*

# Copy FEDn config
COPY config/*.yaml /app/config/

# Setup default environment
COPY environment.yaml /tmp/environment.yaml
RUN conda env create -f /tmp/environment.yaml \
  && rm /tmp/environment.yaml \
  && conda run -n default python -m ipykernel install --name default \
  && chown $USERNAME /opt/conda/envs/default

# Init conda for non-root user
USER $USERNAME
RUN conda init bash \
  && conda config --set auto_activate_base false \
  && echo "conda activate default" >> ~/.bashrc

# Gramine
RUN git clone https://github.com/gramineproject/gramine.git /opt/gramine \
  && pushd /opt/gramine \
  && git checkout $GRAMINE_HEAD \
  && conda run -n default meson setup build/ \
  --buildtype=release -Ddirect=enabled -Dsgx=enabled --prefix=/opt/conda/envs/default \
  && conda run -n default ninja -C build/ \
  && sudo /opt/conda/envs/default/bin/ninja -C build/ install \
  && popd

# Switch back to dialog for any ad-hoc use of apt-get
ENV DEBIAN_FRONTEND=dialog

# Add entrypoint to conda environment for commands
ENTRYPOINT ["conda", "run", "--no-capture-output", "-n", "default"]
```

## Expected results
Enclave printing `mysecret`.

## Actual results
Look at the description.

## Gramine commit hash
`v1.1`

**Comment by dimakuv** [comment]
At a first glance, your setup looks correct. Except the missing `loader.env.SECRET_PROV_blabla` environment variables!

Please check the documentation on Secret Provisioning: https://gramine.readthedocs.io/en/latest/attestation.html#high-level-secret-provisioning-interface.

What you want is the "fully automatic provisioning of the secret string" scenario. For this, you need to specify **3 things**:

1. The hint that secret provisioning should start on construction (immediately, before your Python script).
2. The certificate of the CA that issued the server's certificate.
3. The list of server IP addresses + ports.

What you have is this:
```bash
loader.env.SECRET_PROVISION_CONSTRUCTOR = "1"
loader.env.SECRET_PROVISION_CA_CHAIN_PATH = "certs/client.crt"   # why this weird certificate??
```

So you have the first two things explicitly, and the third thing (the list of servers) is not specified so it is defaulted to `localhost:4433`.

I see two possible bugs here:
1. Are you sure you run both the server and the client on the same machine? You can only use `localhost` address on the same machine, otherwise you need to specify the address explicitly in the `SECRET_PROVISION_SERVERS` envvar.
2. Why do you have `certs/client.crt` file as the CA chain certificate (the root CA)? The name suggests that this is some certificate for this Python application. But what you need is the CA cert that signs the server cert (`server.crt`). In case you're new to SSL/TLS certificates, I recommend to watch https://www.youtube.com/watch?v=Y2yXEjxNG04&t=5s&ab_channel=MattThomas.

> Something is happening but the string is not provisioned in the enclave. What am I missing? I thought that by passing NULL as callback some default logic would be triggered but perhaps this is not the case? Thanks in advance!

Yes, if you pass `NULL` as the callback, then there will be the default logic (of comparing the SGX measurements against user-supplied environment variables). You can skip specifying these environment variables, and nothing bad will happen -- your Secret Provisioning server should work just fine (sending your secret to any SGX enclave, which is completely insecure but we don't care about it for now).

Finally, if you still have issues, we'll need to debug it deeper. The first step would be to set `loader.log_level = "all"` in your Graminized Python app and re-run. This will generate *a lot of logs* from your Python app. Please browse through it, analyze and try to find the part where the SecretProv library connects to the SecretProv C++ server and performs attestation. This will give you an idea at which point things go wrong.

**Comment by mcapuccini** [comment]
Hi! Thanks for such a detailed answer. To answer your questions:

1. Yes. I am running both client and server on localhost.
2. certs/cilent.crt is `test-ca-sha256.crt` from your example folder 

Unfortunately, I wasn't able to figure out what is wrong when working in C++, but the following C program works as expected :)

```c
#include <stddef.h>

#include "secret_prov.h"

int main(int argc, char** argv) {
  secret_provision_start_server((uint8_t*)"mysecret", sizeof("mysecret"),
                                "4433", "certs/server2-sha256.crt",
                                "certs/server2.key", NULL, NULL);
}
```

I will close this issue.
