### ISSUE TITLE
ModuleNotFoundError: No module named 'graminelibos'

### ISSUE THREAD

**Issue by aep** [gramineproject/gramine#492]
sorry this is probably a basic python question, but i just never figured out how python works.

```
[130] aep@stark: CI-Examples/helloworld make
cc -Wall -Wextra -O3   -c -o helloworld.o helloworld.c
cc   helloworld.o   -o helloworld
gramine-manifest \
	-Dlog_level=error \
	helloworld.manifest.template helloworld.manifest
Traceback (most recent call last):
  File "/usr/local/bin/gramine-manifest", line 8, in <module>
    from graminelibos import Manifest
ModuleNotFoundError: No module named 'graminelibos'
make: *** [Makefile:22: helloworld.manifest] Error 1
```

this is after https://gramine.readthedocs.io/en/latest/devel/building.html  

and /usr/local/lib/python3.10/site-packages/graminelibos/  does exist

**Comment by boryspoplawski** [comment]
Actually on my test machine I see only `dist-packages` not `site-packages`  from `/usr/lib`. @woju how should that work?

**Comment by aep** [comment]
PYTHONPATH fixes this, thanks!


this is the default python3 package of archlinux

aep@stark: ~ which python                           
/usr/sbin//python        
aep@stark: ~ python -c 'import sys; print(sys.path)'
['', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '/home/aep/.local/lib/python3.10/site-packages', '/usr/lib/python3.10/site-packages']
aep@stark: ~

**Comment by woju** [comment]
`PYTHONPATH` is a LD_LIBRARY_PATH-level hack and I don't think it should be needed, if you didn't override `--prefix` in `meson setup` (and I presume you didn't, because it's `/usr/local`, right?). So I think this might be a valid bug.

I'd be interested, why Arch's python doesn't have any `/usr/local/*` directory in `sys.path`. Could you point me to a packaging script responsible for shipping `/usr/lib/python3.10/site.py` file?

**Comment by woju** [comment]
Most distros override this file to include LSB/FHS-style `/usr/local` directories while configuring with `--prefix=/usr`. If arch doesn't then I'd say it's a distro-related problem, and on Arch we should suggest people do `meson setup --prefix=/usr`. We have a script to detect "distro-related" problems ([Scripts/get-python-platlib.py](https://github.com/gramineproject/gramine/blob/6de3a9cd0205d27882066daaa8cbea470e0f59f8/Scripts/get-python-platlib.py)), but I'm not willing to install into `/usr` if builddir's prefix is configured to `/usr/local` (even when left as the default).

So the best we can do is to document this in `Documentation/devel/building.rst`. Would you care to add a section there with a point about Arch?

**Comment by eli-schwartz** [comment]
> Most distros override this file to include LSB/FHS-style `/usr/local` directories while configuring with `--prefix=/usr`. If arch doesn't then I'd say it's a distro-related problem

That's some strong language there. The Debian patches to support this are fairly invasive and break pip installing pip. There is upstream Python discussion about trying to resolve this in a way that doesn't leave distros on the hook to patch python, but the future is not clear.

(I believe you already know that their distutils handling is a hot, hot mess.)

**Comment by woju** [comment]
> That's some strong language there.

Yes, you're right, that language has been uncalled for. I'm sorry.

> The Debian patches to support this are fairly invasive and break pip installing pip.

It's not about distutils vs sysconfig which Debian breaks (I'm sure you remember mesonbuild/meson#8739, where we discussed the technical details of that problem). This is more about [`site.py` module](https://docs.python.org/3/library/site.html)), which is _intended_ to be patched by the distribution when they configure python with `--prefix=/usr` and simultaneously want to be compatible with FHS at least to a degree where they support `/usr/local`. It's done by most major distros: [Debian](https://salsa.debian.org/cpython-team/python3/-/blob/99424933f92833162f12f95d393f4605ebed045e/debian/patches/distutils-install-layout.diff#L191), [OpenSUSE](https://salsa.debian.org/cpython-team/python3/-/blob/99424933f92833162f12f95d393f4605ebed045e/debian/patches/distutils-install-layout.diff#L191), [Fedora/RHEL](https://src.fedoraproject.org/rpms/python3.9/blob/rawhide/f/00251-change-user-install-location.patch#_79) etc.

I'm trying to reconcile two desires to both have our `--prefix` honored, and the usual workflow (setup+build+install) work out of the box. In pursuit of this goal I expect the support of the distribution. It's a long established tradition that without intervention, from-source installation is installed to `/usr/local` and meson rightly defaults to this prefix, because there's underlying assumption that distro behaves according to FHS in that regard. Can I say I expect distros to support this convention, or else their users are on their own? (Not to say packagers, because packagers are always on their own). I find Arch's python packaging and/or configuration incomplete in that their shell's `$PATH` seems fine, but python's `site.py` is not.

I don't want to blame either party, if that was Arch's fault or Python's fault, because that wouldn't be constructive. I accept that Python doesn't feel responsible for FHS compatibility (it's distro's call), and at the same time Arch prefers to ship as vanilla as possible. But somewhere in the middle, this means we have no clean way of supporting this, so until gramine gets packaged for Arch with `--prefix=/usr`, instead I'd like to just document this, shall we say, inefficiency, somewhere in our documentation.

**Comment by eli-schwartz** [comment]
Absolutely, this is definitely a pain point that deserves documentation. I just wished to (somewhat inefficiently) point out that debian is actually somewhat non-standard here, and "most distros do it" is a bit inaccurate.

It is true that the single most common distro (Debian and anything inheriting that decision from Debian) does it, as does the second most common (Fedora and anything inheriting from Fedora) but there are a *lot* of other distros out there and I suspect most of them don't do it, including several pretty popular ones.

And doing it is mostly pointless if you're not set up for it, only being useful in I think basically two situations:
- software installed with meson
- software installed with debian-patched pip

And CPython is now aware of the problem and trying to figure out what distros want, but distros are having a slightly hard time defining what they want, so... 🤷‍♂️

**Comment by eli-schwartz** [comment]
Aside: for the sake of clarity, when I said strong language I meant assertive, in the sense of an absolutely qualified truth (something I'm all too often guilty of myself). Maybe a better wording would have been "the word most is doing a lot of work in that sentence".

I hope I did not inadvertently give the impression that I was offended by anything there.

**Comment by woju** [comment]
No, it's OK, thank you. I try not to create unnecessary barriers between us as an upstream and our users and distros, both technical and language-wise. I might have failed today. (I had been also a distro maintainer, and I've been involved in dealing and receiving criticism both ways).

What I want is to have a smooth process for most involved parties, both users and packagers, and I've said "most distros" as a shorthand for "mostly installed distros". I happen to know that our older users mostly use Ubuntu and one of RHEL-derivatives, and right now we gain popularity and widen our userbase, so we're definitely in the process of encountering other, yet undiscovered pain points. I feel the best I can do is optimise for installed base (with `/usr/local` supported as described) and provide tooling for other distros (even as disconnected as NixOS).

For those I would like to agree on a set of clear expectations, both ways, between our dependencies (incl. Python), we as upstream, our users and their distros (incl. Python distros, because all major Linux distros are also Python distros, but I won't discount other Python distros like docker image). I think distros can expect from us at least documentation (the point of this bug), possibly the right tooling and not too many technical barriers.

**Comment by gcecchi** [comment]
I have the same problem after building on Ubuntu 22 and kernel 5.18.

$ meson setup build/ --buildtype=release -Ddirect=enabled -Dsgx=enabled -Ddcap=enabled
$ ninja -C build/
$ sudo ninja -C build/ install
$ gramine-sgx-gen-private-key
$ make SGX=1
cc -Wall -Wextra -O3   -c -o helloworld.o helloworld.c
cc   helloworld.o   -o helloworld
gramine-manifest \
        -Dlog_level=error \
        helloworld.manifest.template helloworld.manifest
Traceback (most recent call last):
  File "/usr/local/bin/gramine-manifest", line 8, in <module>
    from graminelibos import Manifest
ModuleNotFoundError: No module named 'graminelibos'
make: *** [Makefile:22: helloworld.manifest] Error 1
$
$ python -c 'import sys; print(sys.path)'
['', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '/usr/local/lib/python3.10/dist-packages', '/usr/lib/python3/dist-packages']
$ ll /usr/local/graminelibos/
total 76
drwxr-xr-x  2 root root  4096 Oct  5 11:31 ./
drwxr-xr-x 11 root root  4096 Oct  5 11:31 ../
-rw-r--r--  1 root root   955 Oct  5 11:12 __init__.py
-rw-r--r--  1 root root  3613 Oct  5 11:29 _offsets.py
-rw-r--r--  1 root root  7458 Oct  5 11:29 aesm_pb2.py
-rw-r--r--  1 root root  2788 Oct  5 11:10 gen_jinja_env.py
-rw-r--r--  1 root root  6441 Oct  5 11:10 manifest.py
-rw-r--r--  1 root root  5611 Oct  5 11:10 sgx_get_token.py
-rw-r--r--  1 root root 20583 Oct  5 11:10 sgx_sign.py
-rw-r--r--  1 root root  7176 Oct  5 11:10 sigstruct.py
$

$ export PYTHONPATH=/usr/local
$ make SGX=1
cc -Wall -Wextra -O3   -c -o helloworld.o helloworld.c
cc   helloworld.o   -o helloworld
gramine-manifest \
        -Dlog_level=error \
        helloworld.manifest.template helloworld.manifest
gramine-sgx-sign \
        --manifest helloworld.manifest \
        --output helloworld.manifest.sgx
Attributes:
    size:        0x10000000
    thread_num:  4
    isv_prod_id: 0
    isv_svn:     0
    attr.flags:  0x6
    attr.xfrm:   0x3
    misc_select: 0x0
SGX remote attestation:
    None
Memory:
    000000000fffd000-0000000010000000 [REG:R--] (manifest) measured
    000000000ffdd000-000000000fffd000 [REG:RW-] (ssa) measured
    000000000ffd9000-000000000ffdd000 [TCS:---] (tcs) measured
    000000000ffd5000-000000000ffd9000 [REG:RW-] (tls) measured
    000000000ff95000-000000000ffd5000 [REG:RW-] (stack) measured
    000000000ff55000-000000000ff95000 [REG:RW-] (stack) measured
    000000000ff15000-000000000ff55000 [REG:RW-] (stack) measured
    000000000fed5000-000000000ff15000 [REG:RW-] (stack) measured
    000000000fec5000-000000000fed5000 [REG:RW-] (sig_stack) measured
    000000000feb5000-000000000fec5000 [REG:RW-] (sig_stack) measured
    000000000fea5000-000000000feb5000 [REG:RW-] (sig_stack) measured
    000000000fe95000-000000000fea5000 [REG:RW-] (sig_stack) measured
    000000000fa77000-000000000fabd000 [REG:R-X] (code) measured
    000000000fabd000-000000000fe95000 [REG:RW-] (data) measured
    0000000000010000-000000000fa77000 [REG:RWX] (free)
Measurement:
    33d28c3d35d0edca1a31750d2d7d1b242eb44b2d1b4a0b2f45442fdebe024adf
gramine-sgx-get-token \
        --output helloworld.token --sig helloworld.sig
Attributes:
    mr_enclave:  33d28c3d35d0edca1a31750d2d7d1b242eb44b2d1b4a0b2f45442fdebe024adf
    mr_signer:   5b06c74c6d2830ecbc321bd30bab38b3930139a91c6a79271350e483d9da273d
    isv_prod_id: 0
    isv_svn:     0
    attr.flags:  0000000000000006
    attr.xfrm:   00000000000000e7
    mask.flags:  ffffffffffffffff
    mask.xfrm:   fffffffffff9ff1b
    misc_select: 00000000
    misc_mask:   ffffffff
    modulus:     87c2f2139ad90737ddd8dcdb2fa7c0da...
    exponent:    3
    signature:   133b6f9eee541996f21832a65f7ecd79...
    date:        2022-10-05
$

**Comment by dimakuv** [comment]
@woju Do we have any plan what we want to do with this?

**Comment by eli-schwartz** [comment]
It's now possible to use `-Dpython.install_env=system` and have python modules installed into /usr/lib/python3.X even when configured with --prefix=/usr/local.

**Comment by mkow** [comment]
> It's now possible to use `-Dpython.install_env=system` and have python modules installed into /usr/lib/python3.X even when configured with --prefix=/usr/local.

Should we recommend this in our docs? Or maybe disable default `--prefix` as Borys proposes? What are the pros/cons of both?

**Comment by dimakuv** [comment]
I think @woju should have the final word here.
