### ISSUE TITLE
Requirements are missing in .deb release of v1.2-rc1

### ISSUE THREAD

**Issue by Nirusu** [gramineproject/gramine#77]
## Description of the problem
When using the new .deb packages of v1.2-rc1 on a relatively clean system using the instructions listed [in the release](https://github.com/oscarlab/graphene/releases/tag/v1.2-rc1), Graphene cannot be used correctly due to missing Python, protobuf & maybe Intel AESM packages, depending on the environment.

## Steps to reproduce
- Have a fairly clean system with essential development tools
- Install Graphene .deb pre-release as stated in the release notes (I used the out-of-tree DCAP package):
```
sudo apt-key adv --fetch-keys https://packages.grapheneproject.io/graphene.asc
echo 'deb [arch=amd64 signed-by=EA3C2D624681AC968521587A5EE1171912234070] https://packages.grapheneproject.io/ unstable main' | sudo tee /etc/apt/sources.list.d/graphene-unstable.list
sudo apt update
sudo apt install graphene-dcap     # for out-of-tree DCAP driver
```
- Build an application
- Try to sign it with Graphene

## Expected results
Graphene signs the application successfully.

## Actual results
Graphene fails due to missing packages, e.g.:
```
graphene-sgx-sign \
  --key signer-key.pem \
  --manifest redis-server.manifest \
  --output redis-server.manifest.sgx
Traceback (most recent call last):
   File "/usr/bin/graphene-sgx-sign", line 4, in <module>;
   from graphenelibos.sgx_sign import main
   File "/usr/lib/python3/dist-packages/graphenelibos/sgx_sign.py", line 16, in <module>;
   import toml
ModuleNotFoundError: No module named "toml";
make: *** [sgx_outputs] Error 1
Makefile:97: recipe for target 'sgx_outputs' failed
```

## Additional information
I know this is still a pre-release in early stages and the first package, just wanted to "note this down" here as an issue to be fixed for a future packaged release.

Ideally, the package can be directly used within a Docker environment as I am trying to use here (warning: it's a bit messy, haven't really cleaned it up):
https://github.com/edgelesssys/marblerun/commit/1ba7157244a8208df9873029a439dfe3edec6a7a

Note the commented out packages. These contain most of the ones needed to get Graphene to sign the application and return the SIGSTRUCT. However, AESM is still not completely installed as a requirement there. For experiments, I passed the AESM service from the host.

Also, when I am already here creating this issue: Any plans to also adjust your samples to get rid of the GRAPHENEDIR variable, which will not quite work with the release packages?

**Comment by mkow** [comment]
> Don't you want to move this issue to gramine repo?

Done.

**Comment by woju** [comment]
This is fixed in unreleased `1.0~rc2` package. Will keep this open until release.

**Comment by woju** [comment]
Fixed in `v1.0`.
