### ISSUE TITLE
eventfd Function not implemented

### ISSUE THREAD

**Issue by aep** [gramineproject/gramine#772]
trying to start a java springboot hello world,

```
Caused by: java.io.IOException: Function not implemented
	at java.base/sun.nio.ch.EventFD.eventfd0(Native Method) ~[na:na]
	at java.base/sun.nio.ch.EventFD.<init>(EventFD.java:40) ~[na:na]
	at java.base/sun.nio.ch.EPollSelectorImpl.<init>(EPollSelectorImpl.java:82) ~[na:na]
	at java.base/sun.nio.ch.EPollSelectorProvider.openSelector(EPollSelectorProvider.java:36) ~[na:na]
	at java.base/java.nio.channels.Selector.open(Selector.java:295) ~[na:na]
	at org.apache.tomcat.util.net.NioEndpoint$Poller.<init>(NioEndpoint.java:632) ~[tomcat-embed-core-9.0.64.jar!/:na]
	at org.apache.tomcat.util.net.NioEndpoint.startInternal(NioEndpoint.java:311) ~[tomcat-embed-core-9.0.64.jar!/:na]
	at org.apache.tomcat.util.net.AbstractEndpoint.start(AbstractEndpoint.java:1316) ~[tomcat-embed-core-9.0.64.jar!/:na]
	at org.apache.coyote.AbstractProtocol.start(AbstractProtocol.java:614) ~[tomcat-embed-core-9.0.64.jar!/:na]
	at org.apache.catalina.connector.Connector.startInternal(Connector.java:1074) ~[tomcat-embed-core-9.0.64.jar!/:na]
	... 28 common frames omitted

```

looks like the offending call is simply eventfd with no options

https://github.com/openjdk/jdk/blob/739769c8fc4b496f08a92225a12d07414537b6c0/src/java.base/linux/native/libnio/ch/EventFD.c#L38

```C
JNIEXPORT jint JNICALL
Java_sun_nio_ch_EventFD_eventfd0(JNIEnv *env, jclass klazz)
{
    int efd = eventfd((uint64_t)0, 0);
    if (efd == -1) {
        JNU_ThrowIOExceptionWithLastError(env, "eventfd failed");
        return IOS_THROWN;
    }
    return efd;
}
```

**Comment by dimakuv** [comment]
https://gramine.readthedocs.io/en/latest/manifest-syntax.html#allowing-eventfd

**Comment by boryspoplawski** [comment]
But it's not a config error. This function might be insecure and cannot be used in production setups, unless you know exactly what you are doing.

**Comment by dimakuv** [comment]
@aep If you're using the latest Gramine (not the stable release v1.2), then Gramine prints a warning-level message: https://github.com/gramineproject/gramine/blob/cf8095d83b634f37d2c5f33a4d9a7881a11432bc/libos/src/sys/libos_eventfd.c#L37

This should give a hint to a user of Gramine that maybe eventfd should be marked as enabled in the manifest file. (Of course, this message appears with smth like `loader.log_level = "warning"` or `loader.log_level = "debug"` in the manifest file.)
