### ISSUE TITLE
Add `/proc/[pid]/stat` pseudo-file

### ISSUE THREAD

**Issue by dimakuv** [gramineproject/gramine#967]
### Description of the feature

Currently Gramine is missing `/proc/[pid]/stat` pseudo-file. Here is the list of the per-thread (per-process) pseudo-files Gramine emulates: https://github.com/gramineproject/gramine/blob/b491bb9c007b0b0a8e1d360c4cd08a3aa6980ff2/libos/src/fs/proc/fs.c#L26-L33

The `/proc/[pid]/stat` file is required by the `psutil` module of Python. At a minimum, only `[pid] == current process` is enough to emulate; the rest (external processes) can be skipped or emulated in a totally dummy fashion.

Corresponding `psutil` module code that is problematic: https://github.com/giampaolo/psutil/blob/release-5.8.0/psutil/_pslinux.py#L1618-L1619

(See the source code of that function in `_pslinux.py` for a minimal list of fields that need to be emulated in Gramine.)

Here is an example bug report from Python, when trying to run one DLRM PyTorch workload:
```
Traceback (most recent call last):
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/psutil/_common.py", line 447, in wrapper
    ret = self._cache[fun]
AttributeError: _cache

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File <skipped for confidentiality reasons>
    print("current mem usage: {} G".format(psutil.Process(os.getpid()).memory_info().rss / 1024 / 1024 / 1024))
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/psutil/__init__.py", line 326, in __init__
    self._init(pid)
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/psutil/__init__.py", line 354, in _init
    self.create_time()
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/psutil/__init__.py", line 710, in create_time
    self._create_time = self._proc.create_time()
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/psutil/_pslinux.py", line 1576, in wrapper
    return fun(self, *args, **kwargs)
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/psutil/_pslinux.py", line 1788, in create_time
    ctime = float(self._parse_stat_file()['create_time'])
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/psutil/_pslinux.py", line 1576, in wrapper
    return fun(self, *args, **kwargs)
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/psutil/_common.py", line 450, in wrapper
    return fun(self)
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/psutil/_pslinux.py", line 1618, in _parse_stat_file
    with open_binary("%s/%s/stat" % (self._procfs_path, self.pid)) as f:
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/psutil/_common.py", line 711, in open_binary
    return open(fname, "rb", **kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/proc/1/stat'
```

In particular, the workload wants to read the `create_time` field: https://github.com/giampaolo/psutil/blob/b760f4848db4db49de57918660f6a5059666b720/psutil/_pslinux.py#L1636

### Why Gramine should implement it?

Because Python's popular `psutil` package requires it, and doesn't handle the FileNotFound error nicely (at least the tested version 5.8.0).

And just in general, it's good to emulate this file in Gramine.

**Comment by dimakuv** [comment]
@llly will take this task. @llly Can you add a comment with `I will take this task`? Otherwise GitHub doesn't allow to assign you to the task.

**Comment by llly** [comment]
Sure. I will take this task.
